# Example configuration for Landis+Gyr ESPHome component
# This demonstrates all available sensors and configuration options

esphome:
  name: landisgyr_meter
  friendly_name: Smart Meter

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0  # Disable logging over USB

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR_ENCRYPTION_KEY"

ota:
  password: "YOUR_OTA_PASSWORD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case of connection failure
  ap:
    ssid: "Landisgyr Meter Fallback"
    password: "12345678"

# UART Configuration for optical interface
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 300
  data_bits: 7
  parity: EVEN
  stop_bits: 1

# Landis+Gyr Component Configuration
landisgyr:
  uart_id: uart_bus

  # Special Values
  error_code:
    name: "Meter Error Code"
  customer_id:
    name: "Customer ID"
  firmware_version:
    name: "Firmware Version"
  meter_id:
    name: "Meter ID"
  manufacturing_id:
    name: "Manufacturing ID"
  status_flag:
    name: "Status Flag"
  event_power_down_counter:
    name: "Power Down Counter"

  # Security Sensors
  terminal_cover_removal_counter:
    name: "Terminal Cover Removals"
  dc_field_count:
    name: "DC Field Detection Count"

  # Energy Measurements - Total
  positive_active_energy_total:
    name: "Total Import Energy"
    unit_of_measurement: "kWh"
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing
  
  # Energy Measurements - Tariff 1
  positive_active_energy_t1:
    name: "Import Energy T1"
    unit_of_measurement: "kWh"
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  # Energy Measurements - Tariff 2
  positive_active_energy_t2:
    name: "Import Energy T2"
    unit_of_measurement: "kWh"
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  # Export Energy
  negative_active_energy_total:
    name: "Total Export Energy"
    unit_of_measurement: "kWh"
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  # Reactive Energy
  imported_inductive_reactive_energy_total:
    name: "Total Import Reactive Energy"
    unit_of_measurement: "kvarh"
    accuracy_decimals: 3
    state_class: total_increasing

  exported_inductive_reactive_energy_total:
    name: "Total Export Reactive Energy"
    unit_of_measurement: "kvarh"
    accuracy_decimals: 3
    state_class: total_increasing

  # Instantaneous Values - Voltage
  instantaneous_voltage_p1:
    name: "Phase 1 Voltage"
    unit_of_measurement: "V"
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement

  instantaneous_voltage_p2:
    name: "Phase 2 Voltage"
    unit_of_measurement: "V"
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement

  instantaneous_voltage_p3:
    name: "Phase 3 Voltage"
    unit_of_measurement: "V"
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement

  # Instantaneous Values - Current
  instantaneous_current_p1:
    name: "Phase 1 Current"
    unit_of_measurement: "A"
    accuracy_decimals: 2
    device_class: current
    state_class: measurement

  instantaneous_current_p2:
    name: "Phase 2 Current"
    unit_of_measurement: "A"
    accuracy_decimals: 2
    device_class: current
    state_class: measurement

  instantaneous_current_p3:
    name: "Phase 3 Current"
    unit_of_measurement: "A"
    accuracy_decimals: 2
    device_class: current
    state_class: measurement

  # Power Factor
  instantaneous_power_factor:
    name: "Total Power Factor"
    unit_of_measurement: ""
    accuracy_decimals: 3
    state_class: measurement

  instantaneous_power_factor_p1:
    name: "Phase 1 Power Factor"
    unit_of_measurement: ""
    accuracy_decimals: 3
    state_class: measurement

  instantaneous_power_factor_p2:
    name: "Phase 2 Power Factor"
    unit_of_measurement: ""
    accuracy_decimals: 3
    state_class: measurement

  instantaneous_power_factor_p3:
    name: "Phase 3 Power Factor"
    unit_of_measurement: ""
    accuracy_decimals: 3
    state_class: measurement